version: '3.9'

services: 

  web:
    depends_on: 
      - php
    build: ./docker-config/apache
    image: myproject_apache
    container_name: myproject_apache
    ports:
      - "81:80"
      - "443:443"
    volumes: 
      - ./www:/var/www
      - ./docker-config/apache/sites-enabled:/etc/apache2/sites-enabled
    networks: 
      - myproject_net

  php:
    depends_on: 
      - db
    build: ./docker-config/php-composer-symfony
    image: myproject_php-composer-symfony
    container_name: myproject_php
    ports:
      - "82:8000"
    volumes: 
      - ./www:/var/www
    networks:
      - myproject_net

  db:
    image: "mysql:5.7"
    container_name: myproject_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
    networks: 
      - myproject_net

  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin
    container_name: myproject_phpmyadmin
    ports:
      - "83:80"
    environment: 
      - PMA_ARBITRARY=1
    networks: 
      - myproject_net

  node:
    build: ./docker-config/node
    image: myproject_node
    container_name: myproject_node
    ports: 
      - "84:8080"
    volumes:
      - ./www:/home/node/app
    tty: true
    networks: 
      - myproject_net

networks: 
  myproject_net:
volumes: 
  db_data:

